### PR TITLE
Add dotenv support

### PR DESCRIPTION
**Pull request by tomhengatbeyondtrucks**
Add `dotenv` support  and fix a weird error. 

Changelog:
1. Remove useless code.
2. Load dotenv when the tests begin.

### CODE REVIEW

**Comment by tomhengatbeyondtrucks** [comment]
@LeonAran, Could you please review this PR? Thanks very much! 🙇

**Comment by LeonAran** [comment]
@tomhengatbeyondtrucks The above “apiBaseUrl” may need to be deleted, it does not seem to be in effect, but it is afraid that it is suddenly in effect.

**Comment by LeonAran** [comment]
@tomhengatbeyondtrucks 
Oh, not for now, but here's a common method that you might use later.

**Comment by tomhengatbeyondtrucks** [comment]
> @tomhengatbeyondtrucks Oh, not for now, but here's a common method that you might use later.

Thanks for replying, but could you please share more about the `common method`? 🙇

**Pull request merged**
